#!/bin/bash

set -e

searchDirectory=$PWD/$1

echo -e "\e[1;31m Listing pattern '$2' in '$searchDirectory' \e[0m"

hits=$(find $searchDirectory | grep $2)

for hit in $hits
do
    echo -e "\e[1;35m $hit \e[0m"
done
