#!/bin/bash

ranges=("$@")
if [ $# -eq 0 ]; then
    ranges+="192.168.0"
fi

for range in $ranges; do
    for i in {1..254}; do
        (ping $range.$i -c 1 -w 5  >/dev/null && echo "$range.$i" &) ;
    done
done

