#! /bin/bash

cd $HOME
sudo pacman -Syu

sudo pacman -S          \
                        \
     yay                \
     rxvt-unicode       \
                        \
     git                \
     cmake              \
     base-devel         \
     ccache             \
     gcc                \
     valgrind           \
     gdb                \
     expect             \
     zip                \
     unzip              \
     vim                \
     xclip              \
                        \
     smplayer           \
     telegram-desktop   \
     discord            \
                        \
     gnupg              \
     clang              \
     openmp             \
     openmpi            \
     intel-mkl          \
     boost              \
     metis

yay -S                      \
     trilinos               \
     yt-dlp                 \
     spotify                \
     visual-studio-code-bin \
     --sudoloop

# Sources
cd $HOME
mkdir -p git build

cd git
git clone https://github.com/matekelemen/linutils.git
git clone https://github.com/matekelemen/CiE.git --recursive
git clone gttps://github.com/KratosMultiphysics/kratos.git --recursive

python3 linutils/install.py

# Python
cd $HOME
mkdir -p python_venv
cd python_venv

python3 -m venv default --copies
source default/bin/activate
python3 -m pip install  \
    scipy               \
    numpy               \
    matplotlib          \
    vispy               \
    pyqt5		        \
    vitables

# Append PYTHONPATH
sitePackagesDir=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
echo "$HOME/git/kratos/build/FullDebug_gcc/install" >> $sitePackagesDir/pythonpath.pth
echo "$HOME/git/CiE/build/Debug/install/modules" >> $sitePackagesDir/pythonpath.pth
deactivate
cd $HOME

# Edit shell config
echo "alias ll=\"ls -l\"" >> .zshrc
echo "export PATH=$PATH:$HOME/bin" >> .zshrc

# Costumize KDE
$HOME/bin/kdebackground $HOME/git/linutils/background/keqing_wallpaper_custom.png
