#! /bin/bash

cd $HOME
sudo pacman -Syu

sudo pacman -S          \
                        \
     yay                \
     rxvt-unicode       \
                        \
     git                \
     cmake              \
     base-devel         \
     ccache             \
     gcc                \
     valgrind           \
     gdb                \
     expect             \
     zip                \
     unzip              \
     vim                \
     xclip              \
     ttf-meslo-nerd-font-powerlevel10k \
     neovim             \
                        \
     smplayer           \
     telegram-desktop   \
                        \
     gnupg              \
     clang              \
     openmp             \
     intel-mkl          \
     boost

yay -S                      \
     metis-git              \
     trilinos               \
     yt-dlp                 \
     spotify                \
     visual-studio-code-bin \
     --sudoloop

# Sources
cd $HOME
mkdir -p git build

cd git
git clone https://github.com/matekelemen/linutils.git
git clone https://github.com/kelofm/cie.git --recursive
git clone gttps://github.com/matekelemen/krex.git --recursive

python linutils/install.py

# Python
cd $HOME
mkdir -p python_venv
cd python_venv

python -m venv default --copies
source default/bin/activate
python -m pip install   \
    scipy               \
    numpy               \
    matplotlib          \
    pyqt5               \
    mypy
deactivate

# Append paths and configure shell profile
cd $HOME
for profile in ".bash_profile" ".zprofile" ".zshrc"; do
    echo "export PATH=\$PATH:\$HOME/.local/lib:\$HOME/.local/bin" >> $profile
    echo "alias ll=\"ls -l\"" >> $profile
done

# Costumize KDE
# TODO: KDE and XFCE customization
#       - theme
#       - dolphin (especially for XFCE)
#       - terminal emulator (especially for XFCE)
#$HOME/.local/bin/kdebackground $HOME/git/linutils/background/keqing_wallpaper_custom.png
