#! /bin/bash

cd $HOME
sudo pacman -Syu

sudo pacman -S          \
                        \
     yay                \
     rxvt-unicode       \
                        \
     git                \
     cmake              \
     base-devel         \
     ccache             \
     gcc                \
     valgrind           \
     gdb                \
     expect             \
     zip                \
     unzip              \
     vim                \
     xclip              \
     ttf-meslo-nerd-font-powerlevel10k \
                        \
     smplayer           \
     telegram-desktop   \
                        \
     gnupg              \
     clang              \
     openmp             \
     intel-mkl          \
     boost              \
     metis

yay -S                      \
     trilinos               \
     yt-dlp                 \
     spotify                \
     visual-studio-code-bin \
     --sudoloop

# Sources
cd $HOME
mkdir -p git build

cd git
git clone https://github.com/matekelemen/linutils.git
git clone https://github.com/matekelemen/CiE.git --recursive
git clone gttps://github.com/KratosMultiphysics/kratos.git --recursive

python linutils/install.py

# Python
cd $HOME
mkdir -p python_venv
cd python_venv

python -m venv default --copies
source default/bin/activate
python -m pip install   \
    scipy               \
    numpy               \
    matplotlib          \
    vispy               \
    pyqt5               \
    vitables
deactivate

# Append paths
echo "export PATH=\$PATH:\$HOME/.local/lib:\$HOME/.local/bin" >> .bash_profile
echo "export PATH=\$PATH:\$HOME/.local/lib:\$HOME/.local/bin" >> .zprofile
cd $HOME

# Edit shell config
echo "alias ll=\"ls -l\"" >> .zshrc

# Costumize KDE
$HOME/.local/bin/kdebackground $HOME/git/linutils/background/keqing_wallpaper_custom.png
