#!/bin/bash

set -e

printHelp() {
    echo "Decrypt an encrypted file/directory using gpg and a password."
    echo "Usage: decrypt input"
    echo "input     : path to the encrypted item"
}

input="-"
if [ "$#" = 1 ]; then
    input="$1"
    if [ "$input" != "-" ] && [ ! -f "$input" ]; then
        echo "File not found: $input"
        exit 1
    fi
elif [ 1 -lt "$#" ]; then
    echo "decrypt takes at most 1 argument, but $# were given."
    printHelp
    exit 1
fi

gpg -d --quiet "$input" | bsdtar -xO -f -
