#!/bin/bash

#set -e

printHelp() {
    echo "Compress and encrypt a file or directory with zip and gpg."
    echo "Usage: encrypt [OPTIONS]"
    echo "[-h|i:]"
    echo "h     : print help and exit"
    echo "i     : path to input file/direcrory (default is stdin)"
}

isKeyActive=0
for arg in "$@"; do
    if [[ "$arg" == -* ]]; then
        isKeyActive=1
    else
        if [ $isKeyActive = 0 ]; then
            echo "Positional arugments are not supported! (${arg})"
            printHelp
            exit 1
        else
            isKeyActive=0
        fi
    fi
done

input="-"

while getopts "hi:" arg; do
    case "${arg}" in
        h)  # Print help and exit
            printHelp
            exit 0
            ;;
        i)  # Set input path
            input="${OPTARG}"
            if [[ ( "${input}" != "-" ) && ( ! -f "${input}" ) && ( ! -d "${input}" ) ]]; then
                echo "File not found: ${input}"
                exit 2
            fi
            ;;
        \?) # Invalid argument
            "Unrecognized argument: ${OPTARG}"
            exit 3
            ;;
    esac
done

encryptInstruction="gpg --symmetric --no-symkey-cache --cipher-algo AES256"

if [ -d "$input" ]; then
    zip -qq -r - "$input"/* | $encryptInstruction
else
    zip -qq -r - "$input" | $encryptInstruction
fi
