#!/bin/bash

os=$(uname -s)
if [ "$os" == "Linux" ]; then
    decrypt "$HOME/.gitcredentials.gpg" | xclip -selection clipboard
elif [ "$os" == "Darwin" ]; then
    decrypt "$HOME/.gitcredentials.gpg" | pbcopy
else
    echo "Unsupported OS: $os"
fi
