#!/bin/bash

set -e

venvDirectory="$HOME/python_venv"

if [ -d "$venvDirectory" ]; then
    for venvPath in $(ls -d $venvDirectory/*); do
        # Load the virtual environment and get the package list
        source "$venvPath/bin/activate"
        packages=$(python3 -m pip list --format=freeze --disable-pip-version-check | grep -v "^\-e" | cut -d = -f 1)
        deactivate

        read -r -p "Upgrade virtual environment at \"$venvPath\"? [y/N] " confirm
        if [[ "${confirm,,}" =~ ^(yes|y)$ ]]; then
            rm -rf "$venvPath"
            python3 -m venv "$venvPath" --copies
            source "$venvPath/bin/activate"
            python3 -m pip install $packages
            deactivate
        fi
    done
fi
