#! /bin/bash

cd $HOME
sudo pacman -Syu

# System
sudo pacman -S      \
     yay            \
     rxvt-unicode

# Software development - general
sudo pacman -S      \
     git            \
     cmake          \
     base-devel     \
     ccache         \
     gcc            \
     valgrind       \
     gdb            \
     expect         \
     zip            \
     unzip          \
     code

sudo pacman -S          \
     smplayer           \
     yt-dlp             \
     telegram-desktop   \
     discord            \
     spotifyd


# KratosMultiphysics
# hdf5 is installed by trilinos
sudo pacman -S      \
     gnupg          \
     clang          \
     openmp         \
     openmpi        \
     intel-mkl      \
     boost          \
     metis


sudo yay -S trilinos --sudoloop

# Sources
cd $HOME
mkdir -p git build

cd git
git clone https://github.com/matekelemen/bash.git
git clone https://github.com/matekelemen/CiE.git --recursive
git clone gttps://github.com/KratosMultiphysics/kratos.git --recursive

python3 bash/install.py $HOME/bin --config_prefix $HOME

# Python
cd $HOME
mkdir -p python_venv
cd python_venv

python3 -m venv default
source default/bin/activate
python3 -m pip install  \
    scipy               \
    numpy               \
    matplotlib          \
    vispy

# Append PYTHONPATH
sitePackagesDir=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
echo "$HOME/build/kratos/Debug/install" >> $sitePackagesDir/pythonpath.pth
echo "$HOME/git/CiE/build/Debug/install/modules" >> $sitePackagesDir/pythonpath.pth
deactivate
cd $HOME

# Edit shell config
echo "alias ll=\"ls -l\"" >> .zshrc
echo "export PATH=$PATH:$HOME/bin" >> .zshrc

# Costumize KDE
lookandfeeltool -a org.manjaro.breath2-2021-dark.desktop
$HOME/bin/kdebackground $HOME/git/bash/background/keqing_wallpaper_custom.png
